---
- name: install nginx
  hosts: all
  tasks:
    - name: install nginx package
      yum: name=nginx state=installed
    - name: copy nginx.conf
      template:
        src=./nginx.conf.default 
        dest=/etc/nginx/nginx.conf 
        owner=root 
        group=root 
        mode=0644 
        validate='nginx -t -c %s'
      notify:
        - restart nginx service

  handlers:
    - name: restart nginx service
      systemd: name=nginx state=restarted

