# 这里声明git actions的名字
name: publish code

# 指定监听事件，这里监听push到git分支main的事件
on:
  push:
    branches: [ "master" ]

# 这里定义工作流，工作流配置对应job任务
jobs:
  deploy:
    runs-on: ubuntu-latest   

    steps:  
      - uses: actions/checkout@v2  
      - name: Deploy to Server  # 使用别人包装好的步骤，推送文件模块到远程服务器
        uses: AEnterprise/rsync-deploy@v1.0  
        env:
          DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}   #  远程连接的ssh秘钥，引用配置
          ARGS: -avz --delete                       # rsync参数
          SERVER_PORT: '30022'                         # ssh端口
          FOLDER: ./                                # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.REMOTE_HOST }}     # 远程连接的host，引用配置
          USERNAME: ${{ secrets.SSH_USERNAME }}     # 远程连接的用户名，引用配置
          SERVER_DESTINATION: /tmp/optoolkit  # 部署到目标文件的路径

